version: '3.8'

services:
  fsw-barber:
    container_name: fsw-barber
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: barber
      POSTGRES_USER: barber
      POSTGRES_DB: barber-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
